# Generated by Django 4.1 on 2023-07-17 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Required_Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requiredfield_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_works_required', to='DMcoreapp.client_information')),
                ('work_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DMcoreapp.work')),
            ],
        ),
    ]
