# Generated by Django 4.1 on 2023-07-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0003_alter_daily_leeds_exists_date_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='file_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
