# Generated by Django 4.1 on 2023-07-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0005_lead_exe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
