# Generated by Django 4.1 on 2023-07-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0006_lead_lead_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='required_field',
            name='required_task_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
