# Generated by Django 4.1 on 2023-07-21 07:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0007_required_field_required_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_leeds_exists',
            name='date',
            field=models.DateField(default=datetime.date(2023, 7, 21)),
        ),
        migrations.CreateModel(
            name='Smo_socialmedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smo_platform', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('smo_platform_title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('smo_count', models.IntegerField(blank=True, default=0, null=True)),
                ('smo_files', models.FileField(upload_to='smo_files/')),
                ('smo_client_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DMcoreapp.client_information')),
                ('smo_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DMcoreapp.user_registration')),
                ('smo_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DMcoreapp.work')),
            ],
        ),
    ]
