# Generated by Django 4.1 on 2023-07-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0008_alter_daily_leeds_exists_date_smo_socialmedia'),
    ]

    operations = [
        
        
    ]
