# Generated by Django 4.1.4 on 2023-08-03 07:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0010_alter_daily_leeds_exists_date_perfomance'),
    ]

    operations = [
        
        
        
        migrations.AlterField(
            model_name='daily_leeds_exists',
            name='date',
            field=models.DateField(default=datetime.date(2023, 8, 3)),
        ),
        
    ]
