# Generated by Django 4.1.4 on 2023-08-04 05:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0011_progress_report_status_work_tl_id_work_asign_tl_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_leeds_exists',
            name='date',
            field=models.DateField(default=datetime.date(2023, 8, 4)),
        ),
        migrations.CreateModel(
            name='TelecallerPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datamanager_id', models.IntegerField(blank=True, default=0, null=True)),
                ('assign_date', models.DateField(blank=True, null=True)),
                ('assign_lead_count', models.IntegerField(blank=True, default=0, null=True)),
                ('call_lead_count', models.IntegerField(blank=True, default=0, null=True)),
                ('non_call_lead_count', models.IntegerField(blank=True, default=0, null=True)),
                ('performance_data', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('telecaller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DMcoreapp.user_registration')),
            ],
        ),
    ]
