# Generated by Django 4.1.4 on 2023-08-04 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0012_alter_daily_leeds_exists_date_telecallerperformance'),
    ]

    operations = [
       
        
        
        migrations.AlterField(
            model_name='all_leads',
            name='status',
            field=models.CharField(blank=True, default='Non calling', max_length=255, null=True),
        ),
        
       
    ]
