# Generated by Django 4.1.4 on 2023-09-05 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0017_client_information_tl_id_progress_report_status_and_more'),
    ]

    operations = [
       
        
    ]
