# Generated by Django 4.1.4 on 2023-09-06 05:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0019_client_information_assign_status_and_more'),
    ]

    operations = [
       
    ]
