# Generated by Django 4.1.4 on 2023-09-06 06:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0021_client_information_assign_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_information',
            name='assign_status',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='progress_report',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='smo_socialmedia',
            name='smo_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smo_socialmedia',
            name='smo_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='exe_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executive', to='DMcoreapp.user_registration'),
        ),
        migrations.AddField(
            model_name='work',
            name='tl_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='work_asign',
            name='achived',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='work_asign',
            name='delay',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='work_asign',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work_asign',
            name='mail_status',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='work_asign',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work_asign',
            name='status',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='work_asign',
            name='target',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='work_asign',
            name='tl_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='daily_leeds_exists',
            name='date',
            field=models.DateField(default=datetime.date(2023, 9, 6)),
        ),
        migrations.CreateModel(
            name='perfomance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_week', models.IntegerField(blank=True, default=0, null=True)),
                ('previous_status', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('current_week', models.IntegerField(blank=True, default=0, null=True)),
                ('current_status', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('week_perfomance', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('client_perf_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DMcoreapp.client_information')),
                ('client_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DMcoreapp.work')),
                ('pref_exe_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pfromance_exe', to='DMcoreapp.user_registration')),
                ('tl_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pfromance_tl', to='DMcoreapp.user_registration')),
            ],
        ),
        migrations.CreateModel(
            name='CallRecordings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='audio/')),
                ('date', models.DateField(blank=True, null=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DMcoreapp.all_leads')),
                ('telecaller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DMcoreapp.user_registration')),
            ],
        ),
    ]
