# Generated by Django 4.1.4 on 2023-09-08 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0023_remove_client_task_task_head_client_task_task_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_leeds_exists',
            name='date',
            field=models.DateField(default=datetime.date(2023, 9, 8)),
        ),
        migrations.DeleteModel(
            name='Client_Task',
        ),
    ]
