# Generated by Django 4.1.4 on 2023-09-08 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0024_alter_daily_leeds_exists_date_delete_client_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_head', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('Task_txt', models.TextField(blank=True, default='', null=True)),
                ('Task_file', models.ImageField(blank=True, null=True, upload_to='images/requirement/')),
                ('Task_target', models.IntegerField(blank=True, default=0, null=True)),
                ('Task_assign_status', models.IntegerField(blank=True, default=0, null=True)),
                ('Client_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DMcoreapp.client_information')),
                ('Tl_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DMcoreapp.user_registration')),
            ],
        ),
    ]
