# Generated by Django 4.1.4 on 2023-09-08 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0025_client_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='client_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DMcoreapp.client_task'),
        ),
    ]
