# Generated by Django 4.1.4 on 2023-09-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0026_work_client_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_task',
            name='Task_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client_task',
            name='Task_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
