# Generated by Django 4.1.4 on 2023-09-11 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0027_client_task_task_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='assign_status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
       
    ]
